### ISSUE TITLE
数据格式

### ISSUE THREAD

**Issue by terminator123** [necrophagists/ChatGLM2_Lora_Simplified#1]
2023/08/09 数据格式 { {"input":"AAAAA", "output":"BBBBB" }, {"input":"CCCCC", "output":"DDDDD" } }
这个数据格式是不是比较奇怪，也不是dict，也不是list

**Comment by necrophagists** [comment]
这个是json... 我忘记弄代码块了抱歉

**Comment by terminator123** [comment]
> 

json也得是个dict吧。。。还有个错误，data_process.py里面的test_ds =test_dataset.map(str2ids).select_columns(['input_ids','context_len','output_len'])这一行，报str2ids少参数

**Comment by necrophagists** [comment]
已修改
